name: Java Tests with Gradle and Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Install Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-7.3-bin.zip
        unzip -d /opt/gradle gradle-7.3-bin.zip
        export PATH=$PATH:/opt/gradle/gradle-7.3/bin

    - name: Build with Gradle
      working-directory: ${{ github.workspace }}
      run: |
        ./gradlew clean build

    - name: Build Docker Image
      working-directory: ${{ github.workspace }}
      run: |
        docker build -t docker.pkg.github.com/mikaellinushakansson/group3assigntment3/my-java-app:${{ github.ref_name }} .
        
    - name: Push Docker Image
      env:
        DOCKER_PASSWORD: ${{secrets.DOCKER_PAT}}
      run: |
        echo "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" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
        docker push docker.pkg.github.com/mikaellinushakansson/group3assigntment3/my-java-app:${{ github.ref_name }}


  deploy-to-test-environment:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Print Docker Image Name
      run: echo "Docker image to deploy:docker.pkg.github.com/mikaellinushakansson/group3assigntment3/my-java-app:${{ github.ref_name }}"
