name: Java Tests with Gradle and Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Install Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-7.3-bin.zip
        unzip -d /opt/gradle gradle-7.3-bin.zip
        export PATH=$PATH:/opt/gradle/gradle-7.3/bin

    - name: Build with Gradle
      working-directory: ${{ github.workspace }}
      run: |
        ./gradlew clean build

  build-docker-image:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      working-directory: ${{ github.workspace }}
      run: |
        docker build -t docker.pkg.github.com/mikaellinushakansson/group3assigntment3/my-java-app:${{ github.ref_name }} .

  push-docker-image:
    needs: build-docker-image
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker
      env:
        DOCKER_PASSWORD: ${{secrets.DOCKER_PAT}}
      run: |
        echo "${{secrets.DOCKER_PAT}}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Push Docker Image
      run: |
       docker push docker.pkg.github.com/mikaellinushakansson/group3assigntment3/my-java-app:latest


  deploy-to-test-environment:
    needs: push-docker-image
    runs-on: ubuntu-latest

    steps:
    - name: Print Docker Image Name
      run: echo "Docker image to deploy:docker.pkg.github.com/mikaellinushakansson/group3assigntment3/my-java-app:${{ github.ref_name }}"
